;(function(){
  	    angular.module('App',[
            'ui.router',
            'Home',
            'Issues'
      ])
        .config(AppConfig)
  	    .run(AppRun)
        .controller('AppCtrl',AppCtrl)
})();
